### ISSUE TITLE
Current build fails

### ISSUE THREAD

**Issue by fgrunewald** [Tsjerk/Insane#67] opened 2020-10-05 10:30 UTC
Currently the install of insane fails with:
`
Traceback (most recent call last):
  File "bin/insane", line 5, in <module>
    from insane.cli import cli
  File "python3.6/site-packages/insane/__init__.py", line 37, in <module>
    from .core import *
  File "/python3.6/site-packages/insane/core.py", line 35, in <module>
    from simopt import opt_func
ImportError: cannot import name 'opt_func'
`

**Comment by giacomofiorin** [comment] 2020-11-06 23:15
I can confirm this error on Python 3.6.

@Tsjerk @jbarnoud Would you be interested in switching to `argparse` to make it more portable?

**Comment by giacomofiorin** [comment] 2020-12-11 18:18
@Tsjerk @jbarnoud Any comments, please?

Given the wide use of Insane

**Comment by giacomofiorin** [comment] 2020-12-11 18:20
@Tsjerk @jbarnoud Any comments, please?

Given the wide use of Insane:
https://pubs.acs.org/doi/abs/10.1021/acs.jctc.5b00209
it is not unreasonable to ask that, at the very least, you clarify what Python environments are supported by this package.

**Comment by cecilpert** [comment] 2021-06-15 14:21
Hi ! 
I encounter exactly the same issue. Can we expect a working python3 version at some point ? 
Thanks

**Comment by glwhart** [comment] 2023-06-09 15:24
This project seems to be abandoned. I can use the old 2015 insane.py file, but can't seem get this repo running with an up-to-date python. Anyone know whether we'll se   @Tsjerk or @jbarnoud again? This is a really useful package when it's working...

**Comment by mjtadema** [comment] 2023-07-06 09:00
So I don't know why this problem has been hanging around for so long but it works for me on python 3.8.
All I did was manually install simopt from [source](https://github.com/Tsjerk/simopt).
It seems the version of simopt that is on pypi is not compatible with this version of insane.

**Comment by Tsjerk** [comment] 2023-11-30 13:41
This is fixed in simopt.

**Closed by Tsjerk** 2023-11-30 13:41 UTC
